// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djqjpqbsqpeuccdnwhih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqcWpwcWJzcXBldWNjZG53aGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjk5ODMsImV4cCI6MjA2NTUwNTk4M30.257uRKcVC3oRuvU-_3ZvRnW_tloofvwOqpwaWecRjjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);